"""Compact bilingual tables from frozen closure summaries."""
from pathlib import Path
import csv,json,hashlib,shutil

def render(out):
 out=Path(out);root=out.parent;es=out.name=='manuscript_es';manifest={}
 def t(a,b):return b if es else a
 def num(v,n=3):
  s=f'{float(v):.{n}f}';return s.replace('.',',') if es else s
 def source(item,name):
  orig=root/'reports/robustness_closure_v1'/name;dest=out/'tables/data'/item/name;dest.parent.mkdir(parents=True,exist_ok=True)
  if orig.exists():shutil.copyfile(orig,dest)
  with dest.open() as f:rows=list(csv.DictReader(f))
  manifest.setdefault(item,{'sources':[],'rendered_parts':[]})['sources'].append({'source':'reports/robustness_closure_v1/'+name,'included':str(dest.relative_to(out)),'sha256':hashlib.sha256(dest.read_bytes()).hexdigest(),'rows':len(rows)});return rows
 def block(headers,rows,spec=None):
  spec=spec or ('l'+'r'*(len(headers)-1))
  return '\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}'+spec+'@{}}\n\\toprule\n'+' & '.join('\\textbf{'+h+'}' for h in headers)+' \\\\\n\\midrule\n'+'\n'.join(' & '.join(str(v) for v in row)+' \\\\[2pt]' for row in rows)+'\n\\bottomrule\n\\end{tabular*}\n'
 def write(item,caption,body,note):
  text='\\par\\noindent\\begin{minipage}{\\linewidth}\n\\small\n\\setlength{\\tabcolsep}{3pt}\n\\renewcommand{\\arraystretch}{1.15}\n\\captionof{table}{'+caption+'}\\label{tab:'+item+'}\n'+body+'\\par\\smallskip{\\small '+note+'\\par}\n\\end{minipage}\\par\n'
  p=out/'tables/tex'/f'{item}.tex';p.write_text(text);manifest[item].update({'tex':str(p.relative_to(out)),'tex_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'summary_rule':'Frozen final robustness closure, full CSVs included; no calculations rerun.'});manifest[item]['rendered_parts'].append({'caption':caption})
 item='S15';panel=source(item,'model_panel_summary_full_alternatives.csv');source(item,'dimension_alternative_retention.csv');source(item,'morphology_directions.csv')
 names={'specter':'SPECTER','specter2':'SPECTER2','scincl':'SciNCL','scibert':'SciBERT','bert':'BERT','mpnet':'MPNet','minilm':'MiniLM','pubmedbert':'PubMedBERT','biobert':'BioBERT','simcse':'SimCSE'};selected=[r for r in panel if float(r['minimum_relative_difference'])==0];rows=[]
 for p in dict.fromkeys(r['panel'] for r in selected):
  a=next(r for r in selected if r['panel']==p and r['metric']=='angle_p50');b=next(r for r in selected if r['panel']==p and r['metric']=='pr');label=t('All ten','Los diez') if p=='all_ten' else t('Six similarity models','Seis de similitud') if p=='six_similarity' else t('Omit ','Sin ')+names[p[5:]]
  rows.append([label,a['models'],a['contradiction'],a['contradiction_and_alternatives'],b['contradiction'],b['contradiction_and_alternatives']])
 headers=t(['Model panel','Models','Spread',r'\shortstack{Spread +\\alternatives}','PR',r'\shortstack{PR +\\alternatives}'],['Modelos','N','Apertura',r'\shortstack{Apertura +\\alternativas}','PR',r'\shortstack{PR +\\alternativas}'])
 write(item,t('Persistent opposition with full alternative-measure coverage.','Oposición persistente con cobertura completa de medidas alternativas.'),block(headers,rows),t('Counts are out of 325 at zero minimum magnitude. Every angular and dimension alternative now covers all 26 selections. The same opposing models must retain their directions; substitutes do not count. D80 ties remain unresolved. The six-model panel comprises SPECTER, SPECTER2, SciNCL, MPNet, MiniLM and SimCSE. Full cutoffs and directions are supplied as CSVs.','Recuentos sobre 325 con magnitud mínima cero. Todas las alternativas angulares y de dimensión cubren ahora las 26 selecciones. Los mismos modelos opuestos deben conservar sus direcciones; no se sustituyen por otros. Los empates de D80 quedan sin resolver. Los seis modelos son SPECTER, SPECTER2, SciNCL, MPNet, MiniLM y SimCSE. Los CSV conservan cortes y direcciones completos.'))
 item='S18';centres=source(item,'centres_summary.csv');heads=source(item,'headline_summary.csv')
 for name in ['centres_model_pairs.csv','centres_random_reference.csv','centres_nested_sources.csv','centres_omissions.csv','centres_omission_model_pairs.csv','centres_size_rank_stability.csv','headline_grand_repetitions.csv','headline_field_model_stability.csv','headline_models.csv','headline_fields.csv']:source(item,name)
 rows=[]
 for name,label,n in [('repeat256_field',t('26 areas','26 áreas'),256),('repeat256_subfield217',t('217 specialties','217 especialidades'),256),('nested26',t('26 specialties','26 especialidades'),256),('size128_field',t('Areas: size check','Áreas: tamaño'),128),('size256_field',t('Areas: size check','Áreas: tamaño'),256),('size512_field',t('Areas: size check','Áreas: tamaño'),('512') ),('size128_subfield183',t('183 specialties','183 especialidades'),128),('size256_subfield183',t('183 specialties','183 especialidades'),256),('size512_subfield183',t('183 specialties','183 especialidades'),512)]:
  a=next(r for r in centres if r['design']==name and r['grouping']=='observed');b=next(r for r in centres if r['design']==name and r['grouping']=='random');rows.append([label,n,num(a['mean']),num(a['p025'])+'--'+num(a['p975']),num(b['mean'])])
 body=r'\textbf{A. '+t('Centres','Centros')+r'}\par\smallskip'+'\n'+block(t(['Groups','Papers','Mean','Selection range','Random mean'],['Grupos','Artículos','Media','Rango de selección','Media aleatoria']),rows)
 rows=[]
 for recipe,k in [('mean',10),('mean',25),('mean',50),('cls',25),('sep',25)]:
  a={r['measure']:r for r in heads if r['recipe']==recipe and int(r['k'])==k};x=a['title_minus_model'];rows.append([t('Main','Principal') if recipe=='mean' else recipe.upper(),k,num(100*float(a['model_change']['mean']),2),num(100*float(a['title_only_change']['mean']),2),num(100*float(x['mean']),2),num(100*float(x['p025']),2)+t(' to ',' a ')+num(100*float(x['p975']),2)])
 body+='\n\\par\\medskip\\textbf{B. '+t('Neighbour replacement','Sustitución de vecinos')+'}\\par\\smallskip\n'+block(t(['Readout','k',r'\shortstack{Model\\change (\%)}',r'\shortstack{Title only\\(\%)}',r'\shortstack{Difference\\(pp)}','Range (pp)'],['Regla','k',r'\shortstack{Cambio de\\modelo (\%)}',r'\shortstack{Solo título\\(\%)}',r'\shortstack{Diferencia\\(pp)}','Rango (pp)']),rows)
 write(item,t('Repeated centres and direct input--model neighbour contrasts.','Centros repetidos y contraste directo de vecinos entre entrada y modelo.'),body,t('Ranges are 2.5th--97.5th selection percentiles, not confidence intervals. A: 50 selections per row, except 26 specialties (50 specialty choices, ten article selections each). Size checks have their own fixed period quotas. Random groups use the same articles and dates. B: 50 selections, 1,000 candidates per area; difference = title-only replacement minus model-change replacement. No grand-mean sign reversals occur within a readout. CLS/SEP change only four word BERTs.','Rangos entre percentiles 2,5--97,5 de selecciones, no intervalos de confianza. A: 50 selecciones por fila, salvo 26 especialidades (50 elecciones de especialidades y diez selecciones de artículos en cada una). Las pruebas de tamaño tienen sus propias cuotas fijas por período. Los grupos aleatorios usan los mismos artículos y fechas. B: 50 selecciones, 1.000 candidatos por área; diferencia = sustitución con solo título menos sustitución al cambiar modelo. La media no cambia de signo dentro de una regla. CLS/SEP solo cambian cuatro BERT de palabras.'))
 item='S19';q=source(item,'quality_summary.csv');inp=source(item,'quality_input_effects.csv')
 for name in ['quality_fields.csv','quality_model_pairs.csv','quality_input_summary.csv']:source(item,name)
 rows=[]
 for r in q:
  rows.append([t('All','Todos') if r['scope']=='all' else r['scope'],r['cells'],r['k'],num(100*float(r['original_same_query_overlap']),2),num(100*float(r['filtered_overlap']),2),num(r['change_pp'],2)])
 body=block(t(['Candidates','Groups','k','Original (\\%)','Filtered (\\%)','Change (pp)'],['Candidatos','Grupos','k','Original (\\%)','Filtrado (\\%)','Cambio (pp)']),rows)
 rows=[]
 for k in [10,25,50]:
  a=next(r for r in inp if int(r['k'])==k and r['corpus']=='original');b=next(r for r in inp if int(r['k'])==k and r['corpus']=='filtered');rows.append([k,num(100*float(a['model_change']),2),num(100*float(b['model_change']),2),num(100*float(a['title_only_change']),2),num(100*float(b['title_only_change']),2)])
 body+='\n\\par\\medskip\\textbf{'+t('Matched input check: neighbours replaced','Control de entrada emparejado: vecinos sustituidos')+'}\\par\\smallskip\n'+block(['k',t('Model: original','Modelo: original'),t('Model: filtered','Modelo: filtrado'),t('Title: original','Título: original'),t('Title: filtered','Título: filtrado')],rows)
 write(item,t('Quality sensitivity with the same starting papers.','Sensibilidad a la calidad con los mismos artículos de partida.'),body,t('All values except changes are percentages. The filter retains 448,886 articles. The first block holds queries identical before and after filtering; it is distinct from the original all-query mean of 30.29\\% at k25. Fixed-size searches use 100 clean queries included in both pools. Only 63 groups retain 2,048 candidates; all 130 support 1,024. The input check uses 100 queries and 1,000 date-balanced candidates per area, drawn from the saved text panel. It does not test every possible source error or near duplicate.','Todos los valores salvo cambios son porcentajes. El filtro conserva 448.886 artículos. El primer bloque mantiene las mismas consultas antes y después del filtro; es distinto de la media original con todas las consultas, 30,29\\% con k25. Las búsquedas de tamaño fijo incluyen 100 consultas limpias en ambos conjuntos. Solo 63 grupos conservan 2.048 candidatos; los 130 permiten 1.024. El control de entrada usa 100 consultas y 1.000 candidatos equilibrados por fechas en cada área, del panel de texto guardado. No comprueba todo posible error de origen o texto casi duplicado.'))
 item='S20';c=source(item,'morphology_centering_summary.csv');alt=source(item,'dimension_alternative_retention.csv')
 for name in ['morphology_classification.csv','morphology_pairs.csv','morphology_directions.csv','morphology_centering_transitions.csv','morphology_centering_witnesses.csv']:source(item,name)
 rows=[]
 for metric in ['angle_p50','pr']:
  for r in c:
   if r['metric']!=metric:continue
   rows.append([t('Spread','Apertura') if metric=='angle_p50' else 'PR',str(round(100*float(r['cutoff'])))+r'\%',r['original_oppositions'],r['centered_oppositions'],r['same_fixed_witness_directions_retained'],r['new_oppositions'],r['original_oppositions_now_unresolved']])
 body=block(t(['Property','Cutoff','Original','Centred',r'\shortstack{Same models\\and answers}','New',r'\shortstack{Now\\unresolved}'],['Propiedad','Corte','Original','Centrada',r'\shortstack{Mismos modelos\\y respuestas}','Nuevas',r'\shortstack{Ahora sin\\resolver}']),rows)
 rows=[]
 for floor in [0,.01,.05,.1]:
  a={r['alternative']:r for r in alt if float(r['cutoff'])==floor};rows.append([str(round(floor*100))+r'\%',a['both']['PR_oppositions'],a['erank']['same_witness_directions_retained'],a['d80']['same_witness_directions_retained'],a['both']['same_witness_directions_retained']])
 body+='\n\\par\\medskip\\textbf{'+t('PR oppositions retained by the alternatives','Oposiciones de PR conservadas por las alternativas')+'}\\par\\smallskip\n'+block(t(['PR cutoff','Original PR','Entropy','D80','Both'],['Corte de PR','PR original','Entropía','D80','Ambas']),rows)
 write(item,t('Full persistence after centring and under dimension alternatives.','Persistencia completa tras centrar y con alternativas de dimensión.'),body,t('Every condition uses all 26 selections and 325 area pairs. First block: original/centred are total opposition counts; same models and answers requires an original fixed witness pair to keep both directions. New oppositions were not original oppositions. Now unresolved counts original oppositions that become unresolved. At zero cutoff, 142 angular pairs and 204 PR pairs keep the opposition class; same-witness counts are 128 and 204. Reversing both directions occurs for 19 angular witness pairs in ten area pairs, and none for PR; these counts can overlap other categories. Second block: the cutoff applies to PR, while alternatives must preserve nonzero direction in every selection. D80 ties stay unresolved. Full class transitions and witness identities are in the CSV files.','Todas las condiciones usan las 26 selecciones y 325 parejas de áreas. Primer bloque: original/centrada son oposiciones totales; mismos modelos y respuestas exige que una pareja concreta original conserve ambas direcciones. Las oposiciones nuevas no lo eran antes. Ahora sin resolver cuenta oposiciones originales que pasan a esa clase. Con corte cero, 142 parejas angulares y 204 de PR conservan la clase de oposición; con los mismos modelos y direcciones son 128 y 204. Ambas direcciones se invierten en 19 parejas de modelos de diez parejas de áreas para apertura, y en ninguna para PR; estos recuentos pueden solaparse con otras categorías. Segundo bloque: el corte se aplica a PR; las alternativas deben conservar dirección no nula en cada selección. Los empates de D80 quedan sin resolver. Los CSV contienen todas las transiciones e identidades.'))
 p=out/'tables/manifest.json';old=json.loads(p.read_text());old.update(manifest);p.write_text(json.dumps(old,indent=2,ensure_ascii=False)+'\n');return manifest
if __name__=='__main__':render(Path(__file__).resolve().parents[1])
