from pathlib import Path
import json
R=Path('.');H=R/'research/robustness_closure_2026-09-20';B=H/'baseline_documents';changes=[]
def replace_para(text,prefix,new):
 parts=text.splitlines();found=[i for i,p in enumerate(parts) if p.startswith(prefix)];assert len(found)==1,(prefix,found);i=found[0];changes.append({'old':parts[i],'new':new});parts[i]=new;return '\n'.join(parts)+'\n'
en=(B/'manuscript/supplement.tex').read_text();es=(B/'manuscript_es/supplement.tex').read_text()
en=replace_para(en,'Centre comparisons use',r'''Centre comparisons average unit article vectors and scale each centre to unit length before corrected CKA. Direct and weighted-Subfield reconstructions of Field centres were checked for equality. The original matched centres contain 256 articles per group. Its twenty restricted selections change which Subfield represents each Field, not the articles within those Subfields. The repeated centre, size, matched-random and omission analyses now reported in the main text are specified in S9. Random references retain cross-model article correspondence; they are not null tests of independence.''')
es=replace_para(es,'Las comparaciones de centros',r'''Las comparaciones de centros promedian vectores de artículos de longitud uno y ajustan también cada centro a longitud uno antes de calcular la CKA corregida. Se comprobó la igualdad entre los centros de áreas calculados directamente y reconstruidos a partir de especialidades ponderadas. Los centros originales igualados contienen 256 artículos por grupo. Sus veinte selecciones restringidas cambian qué especialidad representa a cada área, no los artículos dentro de esas especialidades. S9 describe las pruebas repetidas de centros, tamaños, grupos aleatorios emparejados y omisiones que se presentan ahora en el artículo. Las referencias aleatorias mantienen la correspondencia de artículos entre modelos; no son pruebas nulas de independencia.''')
en=replace_para(en,'An opposing model pair is retained',r'''An opposing model pair is retained under alternatives only when those same two models preserve their original directions in every alternative. Angular alternatives, entropy dimension and D80 now all cover the primary selection, twenty half samples and five additional selections: 26 conditions each. The original three-condition dimension check is preserved as history; Table S15 uses the completed coverage. D80 is discrete and ties remain unresolved. At positive cutoffs, PR must exceed the stated minimum; its alternatives must preserve nonzero direction. Models are not replaced with different witnesses to preserve a count. Ten leave-one-model panels and the six similarity-oriented models test panel dependence; smaller panels offer fewer opportunities for opposition.''')
es=replace_para(es,'Una pareja de modelos opuestos se conserva',r'''Una pareja de modelos opuestos se conserva con las alternativas solo cuando esos mismos dos modelos mantienen sus direcciones originales en todas ellas. Las alternativas angulares, la dimensión por entropía y D80 cubren ahora la selección principal, veinte mitades y cinco selecciones adicionales: 26 condiciones cada una. La comprobación original de dimensión con tres condiciones se conserva como historial; la Tabla S15 usa la cobertura completa. D80 es discreta y sus empates quedan sin resolver. Con cortes positivos, PR debe superar el mínimo indicado; sus alternativas deben conservar dirección no nula. No se sustituyen los modelos por otros para mantener un recuento. Diez conjuntos que omiten un modelo y los seis modelos de similitud comprueban la dependencia del conjunto; los conjuntos pequeños ofrecen menos oportunidades de oposición.''')
# Exact interpolation convention in the frozen implementation; no measure changed.
en=en.replace(r'angular spread is the median of $\arccos(u_i^\top u_j)$, reported in degrees.',r'angular spread uses the median pairwise chord distance, converted to degrees as $2\arcsin(q_{0.5}(\lVert u_i-u_j\rVert)/2)$. The saved implementation interpolates distance quantiles before this monotone conversion; the same convention is retained throughout.')
# Spanish formula paragraph has the same original mathematical expression.
es=es.replace(r'la apertura angular es la mediana de $\arccos(u_i^\top u_j)$, expresada en grados.',r'la apertura angular utiliza la mediana de la distancia entre pares, convertida a grados como $2\arcsin(q_{0.5}(\lVert u_i-u_j\rVert)/2)$. La implementación guardada interpola los cuantiles de distancia antes de esta conversión monótona; se mantiene la misma convención en todo el análisis.')
new_en=r'''\clearpage
\section{Final targeted robustness checks}
These checks were specified after the previous results and the draft, before their new outcomes were inspected. They reuse the frozen vectors, preserve all earlier outputs and address the remaining selection, processing and source-quality questions. They add no model training or corpus extraction. Tables S18--S20 are accompanied by unrounded CSV summaries; the repository's \nolinkurl{data/robustness_closure_v1/} holds selections, source snapshots and per-part checksums. \nolinkurl{ROBUSTNESS_CLOSURE_PROTOCOL.md} records the design. The source package reproduces this display, not the unavailable corpus.

\subsection{Repeated centres and direct neighbour contrasts}
The 256-article centre check uses fifty selections of the same 26 Fields and 217 Subfields. Within each group, selection preserves the original five period counts. The size check fixes 26 Fields and 183 Subfields at 128, 256 and 512 articles; each has fifty repetitions. Period quotas derive from the original 512-article prefix, with nested largest-remainder rounding for smaller sizes. Thus its 256-article quotas differ from the first check. One within-period reassignment accompanies every selection, using exactly the same articles across observed/random groups and models.

The restricted comparison selects one eligible Subfield per Field fifty times, then selects articles ten times within each choice. Between-choice standard deviation of the observed mean is 0.01205; mean within-choice standard deviation is 0.00157. These are descriptive components, not independent population variances. The old restricted random reference drew 26 centres from a reassignment across all 217 Subfields; the new reference instead shuffles exactly the selected 26 groups' articles. Omitting each Field from the original centres changes mean CKA by at most 0.00687, for Mathematics; the largest individual model-pair shift is 0.02355 for MiniLM--BioBERT. All omissions are also calculated across the fifty new selections.

For direct neighbour stability, each of fifty selections draws 200 papers per Field and period from the text experiment: 1,000 candidates per Field. Queries and candidates coincide; self matches are excluded. Full exact candidate rankings can be restricted to these subsets without changing the search. Independent direct sorting checks 4,680 queries, in addition to synthetic checks with tied vectors. The contrast averages the ten same-model title changes and the 45 between-model title-plus-abstract changes, weighting Fields equally. A model-specific reference averages its nine model comparisons. Main k values are 10, 25 and 50; CLS/SEP affect only the four word BERTs and are checked at k25. Model-specific mean contrasts range from $-14.04$ to $+16.59$ percentage points; Field means range from $-4.43$ to $+5.63$. The grand mean is not a universal ordering or an equivalence test.
\input{tables/tex/S18}
\FloatBarrier
\PanelFigure{figure_S11}{Additional selection checks. (A) Centre agreement at three article counts; solid lines show observed groups and dashed lines show matched random groups. Shading spans 2.5th--97.5th percentiles of fifty selection means. The same 183 Subfields are used throughout. (B) Each point is one of fifty balanced selections in the direct neighbour test. Positive values mean that removing the abstract changes more neighbours than changing models; negative values mean the reverse. Black marks are medians. Main uses the primary recipes; CLS/SEP change only the four word BERTs. Neither panel supplies population confidence intervals.}{closure}{1}
\FloatBarrier

\subsection{Quality filtering with matched queries}
The existing strict filter removes seven flagged categories and retains the lowest row index in each connected component of identical nonempty DOI or normalised text. This is not a new near-duplicate detector. It retains 448,886 records. Full searches compare every surviving query against original and filtered candidates in its Field-period group. At k25, the original all-query mean is 30.29\%; restricting queries alone gives 30.58\%, and filtering their candidates gives 31.43\%. The matched-query gain is 0.85 points, or 0.77 after the existing chance adjustment.

The equal-count controls include the same 100 clean queries in both candidate pools, filling remaining places by deterministic random order. All 130 cells support 1,024 candidates; only 63 support 2,048. The largest Field-average change in full searches is 2.72 points in Mathematics. Across model pairs, the largest mean gain is 1.43 points for SPECTER2--SciBERT. The 52,000-paper text panel has at least 235 clean papers per Field-period cell. It supports 200 candidates and twenty clean queries per period in both arms, or 1,000 candidates and 100 queries per Field. Thus candidate counts, dates and queries stay matched. All k values retain substantial model disagreement. The filter's limited coverage prevents concluding that all source errors are harmless.
\input{tables/tex/S19}
\FloatBarrier

\subsection{Complete processing and dimension checks}
For each model, the global mean is calculated once from its 52,000 unit vectors. Every original unit vector in each saved selection has that mean subtracted, then is normalised again. The mean is not recalculated per Field or repetition. Covariance centring alone would leave PR unchanged; the subsequent row normalisation makes this a different representation. Spread and PR use the original main selection, twenty halves and five further equal-size selections. Entropy dimension and D80 are completed on those same 26 original selections. No selection or magnitude cutoff is changed.

The classes and fixed-model direction rules remain those of S7. At zero cutoff, 142 original angular oppositions keep the opposition class after centring, but only 128 keep an original model pair with both directions unchanged; nine new oppositions give 151 in total. PR retains 204 original oppositions and adds seven, giving 211. The same-direction requirement also retains only five of the original 54 all-ten PR agreements jointly under entropy and D80; many comparisons cannot satisfy a rule requiring every model to retain a nonzero ordering. D80 ties stay unresolved. All class transitions, reversed witness directions and magnitude checks are included, not just favourable retentions.
\input{tables/tex/S20}
\FloatBarrier

The numerical audit independently reproduces 78,000 model-specific directions using equivalent ratio inequalities, reproduces the saved original neighbour means to numerical precision, and verifies all 900 centre selections and matched references. None of these checks establishes thematic accuracy, independence of overlapping selections or population precision. The main text therefore distinguishes stable averages from 2,628 local selection alerts among 8,235 Subfield--model-pair comparisons.'''
new_es=r'''\clearpage
\section{Últimas comprobaciones dirigidas de robustez}
Estas pruebas se definieron después de los resultados anteriores y del borrador, antes de inspeccionar sus nuevos resultados. Reutilizan los vectores congelados, conservan las salidas anteriores y responden a las cuestiones pendientes de selección, procesamiento y calidad de origen. No añaden entrenamiento ni extracción. Los archivos CSV de las Tablas S18--S20 incluyen resúmenes sin redondear; \nolinkurl{data/robustness_closure_v1/} conserva selecciones, copias de programas y huellas por parte. \nolinkurl{ROBUSTNESS_CLOSURE_PROTOCOL.md} registra el diseño. El paquete fuente reproduce esta presentación, no el corpus que no se distribuye.

\subsection{Centros repetidos y contrastes directos de vecinos}
La prueba de centros con 256 artículos utiliza cincuenta selecciones de las mismas 26 áreas y 217 especialidades. Cada grupo conserva sus cinco recuentos originales por período. La prueba de tamaño fija 26 áreas y 183 especialidades con 128, 256 y 512 artículos, y cincuenta repeticiones. Las cuotas por período proceden del prefijo original de 512 artículos y se redondean de forma anidada por restos mayores para los tamaños menores. Por eso sus cuotas de 256 artículos difieren de las de la primera prueba. Cada selección tiene una reasignación dentro de períodos, con exactamente los mismos artículos entre grupos observados/aleatorios y modelos.

La comparación restringida elige una especialidad elegible por área cincuenta veces, y después selecciona artículos diez veces dentro de cada elección. La desviación típica entre medias de elecciones de especialidades es 0,01205; la desviación típica media dentro de cada elección es 0,00157. Son componentes descriptivos, no varianzas poblacionales independientes. La referencia aleatoria restringida antigua tomaba 26 centros de una reasignación de las 217 especialidades; la nueva mezcla exactamente los artículos de los 26 grupos elegidos. Omitir cada área de los centros originales cambia la CKA media como máximo 0,00687, al omitir Matemáticas; el mayor cambio de una pareja de modelos es 0,02355 para MiniLM--BioBERT. También se calculan todas las omisiones en las cincuenta selecciones nuevas.

Para comprobar directamente los vecinos, cada una de cincuenta selecciones toma 200 artículos por área y período del experimento de texto: 1.000 candidatos por área. Consultas y candidatos coinciden; se excluye el propio artículo. El orden completo y exacto de candidatos puede restringirse a estos subconjuntos sin cambiar la búsqueda. Una ordenación directa independiente comprueba 4.680 consultas, además de pruebas artificiales con vectores empatados. El contraste promedia los diez cambios de título dentro de cada modelo y los 45 cambios entre modelos con título y resumen, dando el mismo peso a cada área. La referencia de cada modelo promedia sus nueve comparaciones con otros. Los valores principales de k son 10, 25 y 50; CLS/SEP solo afectan a los cuatro BERT de palabras y se comprueban con k25. Las diferencias medias por modelo van de $-14,04$ a $+16,59$ puntos porcentuales; las medias por área, de $-4,43$ a $+5,63$. La media general no es un orden universal ni una prueba de equivalencia.
\input{tables/tex/S18}
\FloatBarrier
\PanelFigure{figure_S11}{Comprobaciones adicionales de selección. (A) Acuerdo entre centros con tres cantidades de artículos; las líneas continuas representan grupos observados y las discontinuas, grupos aleatorios emparejados. El sombreado abarca los percentiles 2,5--97,5 de cincuenta medias de selección. Se mantienen las mismas 183 especialidades. (B) Cada punto es una de cincuenta selecciones equilibradas en la prueba directa de vecinos. Un valor positivo significa que quitar el resumen cambia más vecinos que cambiar modelo; uno negativo significa lo contrario. Las marcas negras son medianas. Base usa las reglas principales; CLS/SEP solo cambian los cuatro BERT de palabras. Ningún panel ofrece intervalos de confianza poblacionales.}{closure}{1}
\FloatBarrier

\subsection{Filtro de calidad con consultas emparejadas}
El filtro estricto existente excluye siete categorías marcadas y conserva el menor índice de fila de cada componente conectado por DOI no vacío o texto normalizado idéntico. No es un detector nuevo de textos casi duplicados. Conserva 448.886 registros. Las búsquedas completas comparan cada consulta conservada con candidatos originales y filtrados de su grupo de área y período. Con k25, la media original de todas las consultas es 30,29\%; restringir solo las consultas da 30,58\%, y filtrar sus candidatos da 31,43\%. La subida con las mismas consultas es de 0,85 puntos, o 0,77 con el ajuste por azar existente.

Los controles de cantidad igual incluyen las mismas 100 consultas limpias en ambos conjuntos y completan los candidatos por orden aleatorio determinista. Las 130 celdas permiten 1.024 candidatos; solo 63 permiten 2.048. El mayor cambio medio por área en las búsquedas completas es de 2,72 puntos en Matemáticas. Entre parejas de modelos, la mayor subida media es de 1,43 puntos para SPECTER2--SciBERT. El panel de texto de 52.000 artículos tiene al menos 235 artículos limpios por celda de área y período. Permite usar 200 candidatos y veinte consultas limpias por período en ambos grupos: 1.000 candidatos y 100 consultas por área. Así se mantienen iguales cantidades, fechas y consultas. Todos los valores de k conservan un desacuerdo importante entre modelos. La cobertura limitada del filtro impide concluir que todos los errores de origen sean inocuos.
\input{tables/tex/S19}
\FloatBarrier

\subsection{Comprobaciones completas de procesamiento y dimensión}
La media global se calcula una sola vez por modelo a partir de sus 52.000 vectores unitarios. A cada vector unitario original de cada selección guardada se le resta esa media y después se vuelve a normalizar. La media no se recalcula por área ni repetición. Centrar solo la covarianza dejaría PR igual; normalizar después cada fila produce una representación distinta. Apertura y PR usan la selección principal original, veinte mitades y cinco selecciones adicionales del mismo tamaño. La dimensión por entropía y D80 se completan en esas mismas 26 selecciones originales. No cambia ninguna selección ni corte de magnitud.

Se mantienen las clases y reglas de dirección por modelo de S7. Con corte cero, 142 oposiciones angulares originales conservan la clase de oposición tras centrar, pero solo 128 conservan una pareja de modelos original con ambas direcciones iguales; nueve oposiciones nuevas dan 151 en total. PR conserva 204 oposiciones originales y añade siete, para un total de 211. Exigir la misma dirección también conserva solo cinco de los 54 acuerdos originales de los diez modelos en PR con entropía y D80 a la vez; muchas comparaciones no pueden cumplir una regla que exige un orden no nulo en cada modelo. Los empates de D80 quedan sin resolver. Se incluyen todas las transiciones, inversiones de los modelos concretos y cortes de magnitud, no solo las conservaciones favorables.
\input{tables/tex/S20}
\FloatBarrier

La auditoría numérica reproduce de forma independiente 78.000 direcciones específicas de modelos mediante desigualdades equivalentes entre cocientes, reproduce las medias originales de vecinos con precisión numérica y verifica las 900 selecciones de centros y sus referencias emparejadas. Ninguna prueba demuestra corrección temática, independencia entre selecciones solapadas o precisión poblacional. Por eso el artículo distingue medias estables de 2.628 alertas locales entre 8.235 comparaciones de especialidad y pareja de modelos.'''
needle='\\FloatBarrier\n\\bibliographystyle{plainnat}'
assert needle in en and needle in es
en=en.replace(needle,new_en+'\n\n'+needle);es=es.replace(needle,new_es+'\n\n'+needle)
(R/'manuscript/supplement.tex').write_text(en);(R/'manuscript_es/supplement.tex').write_text(es)
(H/'supplement_changes.json').write_text(json.dumps(changes,indent=2,ensure_ascii=False)+'\n')
print('Supplement updated in both languages.')
