from pathlib import Path
import json
R=Path('.');HERE=R/'research/robustness_closure_2026-09-20';B=HERE/'baseline_documents'
assert json.loads((R/'data/robustness_closure_v1/summary/audit.json').read_text())['all_complete']
assert json.loads((HERE/'independent_scientific_audit.json').read_text())['passed']
en=(B/'manuscript/main.tex').read_text().split('\n\n');es=(B/'manuscript_es/main.tex').read_text().split('\n\n');changes=[]
def setp(i,a,b,reason,source):
 changes.append({'section_index':i,'old_en':en[i],'new_en':a,'old_es':es[i],'new_es':b,'reason':reason,'evidence':source});en[i]=a;es[i]=b
setp(1,r'''\begin{abstract}
Science maps use relationships between papers to describe how research is organised. When these relationships come from text embeddings, a model turns each paper into a list of numbers. Would another model give the same picture? I compare ten models using the same collection of 500,000 OpenAlex records, covering 26 research fields and 2000--2024. I examine the overall arrangement, the papers placed closest to each other, and the spread of papers within fields. The broad arrangement survives repeated article selections and changes in group size. Yet, within the same field and period, two models retain about eight of the same 25 closest papers on average. Removing the abstract produces a similarly large average change, with substantial differences between models and processing rules. Models also give opposite answers about which field has more widely spread representations. Some answers persist across article selections but change when the same vectors are prepared for comparison in a different way. Repeating a result with other articles therefore does not ensure that it survives another model or processing choice. These checks locate dependence on representation; they do not establish which model best describes the research itself.
\end{abstract}
\textbf{Keywords:} science mapping; document embeddings; robustness; neighbourhood agreement; geometric comparisons.''',r'''\begin{abstract}
Los mapas de la ciencia usan las relaciones entre artículos para describir cómo se organiza la investigación. Cuando esas relaciones proceden de embeddings de texto, un modelo convierte cada artículo en una lista de números. \textquestiondown{}Otro modelo daría la misma imagen? Comparo diez modelos con la misma colección de 500.000 registros de OpenAlex, que cubre 26 áreas y 2000--2024. Examino la organización general, los artículos más próximos y la dispersión dentro de las áreas. La organización general se mantiene al elegir otros artículos y cambiar el tamaño de los grupos. Aun así, dentro de una misma área y período, dos modelos conservan en promedio unos ocho de los mismos 25 artículos más próximos. Quitar el resumen produce un cambio medio parecido, con diferencias importantes entre modelos y reglas de procesamiento. Los modelos también dan respuestas opuestas sobre qué área tiene representaciones más dispersas. Algunas respuestas persisten al elegir otros artículos, pero cambian al preparar los mismos vectores de otra manera. Repetir un resultado con otros artículos no garantiza, por tanto, que se mantenga con otro modelo o procesamiento. Estas comprobaciones sitúan la dependencia de la representación; no establecen qué modelo describe mejor la investigación.
\end{abstract}
\textbf{Palabras clave:} mapas de la ciencia; embeddings de documentos; robustez; acuerdo de vecindarios; comparaciones geométricas.''','Matizar entrada y apertura; reforzar centros con repeticiones.','summary.json')
setp(23,en[23].replace('I average its article vectors to obtain a centre.','I average its article vectors and scale that centre to length one as well.'),es[23].replace('Para resumir un área, calculo la media de sus vectores y obtengo un centro.','Para resumir un área, calculo la media de sus vectores y ajusto también ese centro a longitud uno.'),'Explicitar la normalización de los centros que ya realizaba el código.','PHASE0_AUDIT.md')
# Make the Spanish operation explicit even if its previous wording differs.
if 'ajusto también ese centro' not in es[23]:
 old=es[23];es[23]=r'''\subsection{Del conjunto de áreas a los artículos individuales}
Antes de comparar las representaciones, cada vector se ajusta para que tenga longitud uno. Así, las comparaciones dependen de su dirección y no de su longitud. Para resumir un área, calculo la media de sus vectores y ajusto también ese centro a longitud uno. La posición relativa de los centros describe las relaciones generales entre áreas. Comparar los vectores de los artículos dentro de cada área conserva el detalle que esa media oculta.''';changes[-1]['new_es']=es[23]
setp(24,r'''The original centre comparison uses 256 articles per centre: 26 areas, 217 specialties, or one specialty from each area. I then repeat article selection fifty times, keeping each group's period counts. A size check uses 128, 256 and 512 papers, with the same 26 areas and 183 eligible specialties. Each selection has a random-group reference made from exactly the same articles and date counts. Further checks omit each area and separate the choice of specialty from the choice of its papers. These centre comparisons are distinct from comparing individual vectors within groups (Supplement S9).''',r'''La comparación original utiliza 256 artículos por centro: 26 áreas, 217 especialidades o una especialidad de cada área. Después repito cincuenta veces la elección de artículos, conservando los recuentos por período de cada grupo. Otra comprobación utiliza 128, 256 y 512 artículos, con las mismas 26 áreas y 183 especialidades que tienen suficientes trabajos. Cada selección tiene una referencia de grupos aleatorios formada con exactamente los mismos artículos y fechas. Otras pruebas omiten cada área y separan la elección de especialidades de la elección de sus artículos. Comparar estos centros es distinto de comparar los vectores individuales dentro de los grupos (Suplemento S9).''','Describir repetición, tamaños, referencia y omisiones.','centres_summary.csv; centres_random_reference.csv')
setp(25,en[25]+r'''

The quality check applies the existing flags and duplicate rule, leaving 448,886 records. It compares the same retained starting papers before and after filtering candidates. Equal-size controls use 1,024 candidates in all 130 groups and 2,048 in the 63 groups large enough after filtering. They include the same 100 clean starting papers in both candidate sets. A separate text check matches dates and candidate counts inside the 52,000-paper experiment. These controls test the recorded filter, not every possible source error.''',es[25]+r'''

La comprobación de calidad aplica las marcas y la regla de duplicados existentes, y conserva 448.886 registros. Compara los mismos artículos de partida antes y después de filtrar los candidatos. Los controles de tamaño fijo usan 1.024 candidatos en los 130 grupos y 2.048 en los 63 que siguen teniendo suficientes artículos después del filtro. Ambos conjuntos incluyen los mismos 100 artículos de partida limpios. Otra prueba de texto iguala fechas y candidatos dentro del experimento de 52.000 artículos. Estos controles comprueban el filtro registrado, no todos los posibles errores de origen.''','Añadir el control de calidad de vecinos con consultas comparables.','quality_summary.csv; quality_input_summary.csv')
# Raw strings above use literal separators; turn only these intended paragraph separators into newlines.
en[25]=en[25].replace(r'\n\n','\n\n');es[25]=es[25].replace(r'\n\n','\n\n');changes[-1]['new_en']=en[25];changes[-1]['new_es']=es[25]
setp(28,en[28].replace('it is the median angle between distinct vectors.', 'it summarises the angles between distinct vectors, using the median-distance convention in Supplement S6.'),es[28].replace('es la mediana del ángulo entre vectores distintos.', 'resume los ángulos entre vectores distintos, con la regla de distancia mediana del Suplemento S6.'),'Mantener la explicación sencilla y remitir a la convención exacta de cuantiles.','PHASE0_AUDIT.md; supplement S6')
setp(29,en[29].replace('The dimension alternatives use the same underlying variation,', 'For dimension, one alternative measures how evenly variation is distributed (entropy-based dimension); another counts the directions needed to account for 80\% of it (D80). These alternatives use the same underlying variation,'),es[29].replace('Las alternativas de dimensión utilizan la misma variación de partida,', 'Para dimensión, una alternativa mide cómo se reparte la variación (dimensión por entropía); otra cuenta las direcciones necesarias para explicar el 80\% de ella (D80). Estas alternativas utilizan la misma variación de partida,'),'Explicar las alternativas antes de citarlas por nombre en resultados.','METHODS_MORPHOLOGY.md; supplement S6')
setp(30,en[30]+r''' The two dimension alternatives now cover the same 26 selections. I also repeat the spread and dimension comparisons after subtracting the mean of the balanced 52,000 unit vectors and scaling each resulting vector back to length one. This tests a changed representation, not merely the covariance centring used to calculate PR.''',es[30]+r''' Las dos alternativas de dimensión cubren ahora las mismas 26 selecciones. También repito las comparaciones de apertura y dimensión después de restar la media de los 52.000 vectores unitarios equilibrados y ajustar cada vector resultante a longitud uno. Esto cambia la representación; no es simplemente el centrado de la covarianza que se utiliza para calcular PR.''','Igualar cobertura y definir exactamente el cambio de referencia.','morphology_classification.csv; dimension_alternative_retention.csv')
setp(34,r'''\section{Results}
\FloatBarrier
\subsection{The broad arrangement is shared more than the detail}
The broad arrangement repeats when different papers are selected. The original mean corrected CKA values of 0.939 for area centres and 0.911 for specialty centres become 0.940 and 0.911 across fifty selections. Their central 95\% selection ranges are 0.937--0.943 and 0.910--0.912 (Figure~\ref{fig:scales}A). Random groups average 0.627 and 0.636; none of their selection means reaches the lowest observed selection mean.

The size check gives area-centre means of 0.938, 0.940 and 0.941 at 128, 256 and 512 papers; the same 183 specialties give 0.913, 0.914 and 0.915. Omitting one area from the original comparison gives 0.933--0.946. No single area accounts for the high overall agreement. Choosing one specialty per area gives a mean of 0.904: which specialty is chosen matters more than which papers are chosen within it (Table S18).
\PanelFigure{figure_01}{Agreement about area summaries and the papers inside them. Higher corrected CKA means greater agreement between models. (A) Means across fifty article selections with 256 papers per centre; the 26-specialty condition uses fifty specialty choices with ten article selections each. Random groups use the same articles, sizes and dates. Whiskers show 2.5th--97.5th percentiles of selection means. (B) Agreement within groups at three article counts, using 26 areas and the same 183 specialties. Points show means; lines span the 2.5th--97.5th percentiles of group--model-pair results: 1,170 for areas and 8,235 for specialties. These spreads describe different sources of variation; neither is a confidence interval. The panels compare different objects, not a causal effect of scale.}{scales}{1}''',r'''\section{Resultados}
\FloatBarrier
\subsection{La organización general se comparte más que el detalle}
La organización general se repite al elegir otros artículos. Las medias originales de CKA corregida de 0,939 para centros de áreas y 0,911 para centros de especialidades pasan a 0,940 y 0,911 en cincuenta selecciones. Sus rangos centrales del 95\% entre selecciones son 0,937--0,943 y 0,910--0,912 (Figura~\ref{fig:scales}A). Los grupos aleatorios dan medias de 0,627 y 0,636; ninguna de sus medias alcanza la menor media observada.

La comprobación de tamaño da medias entre centros de áreas de 0,938, 0,940 y 0,941 con 128, 256 y 512 artículos; las mismas 183 especialidades dan 0,913, 0,914 y 0,915. Omitir un área de la comparación original da 0,933--0,946. Ninguna área por sí sola explica el alto acuerdo general. Elegir una especialidad por área da una media de 0,904: importa más qué especialidad se elige que qué artículos se eligen dentro de ella (Tabla S18).
\PanelFigure{figure_01}{Acuerdo sobre los resúmenes de áreas y sobre sus artículos. Una CKA corregida mayor indica más acuerdo entre modelos. (A) Medias de cincuenta selecciones con 256 artículos por centro; la condición de 26 especialidades usa cincuenta elecciones de especialidades y diez selecciones de artículos por elección. Los grupos aleatorios usan los mismos artículos, tamaños y fechas. Las líneas muestran los percentiles 2,5--97,5 de las medias entre selecciones. (B) Acuerdo dentro de grupos con tres cantidades de artículos, 26 áreas y las mismas 183 especialidades. Los puntos son medias; las líneas abarcan los percentiles 2,5--97,5 de los resultados de grupo y pareja de modelos: 1.170 para áreas y 8.235 para especialidades. Los rangos describen fuentes de variación distintas; ninguno es un intervalo de confianza. Los paneles comparan objetos distintos, no un efecto causal de la escala.}{scales}{1}''','Sustituir el valor único por la evidencia repetida y conservar el contraste de objetos.','centres_summary.csv; centres_omissions.csv; centres_nested_sources.csv')
setp(35,r'''Inside groups, mean CKA remains around 0.63 for areas and 0.64 for the same 183 specialties from 128 to 512 articles (Figure~\ref{fig:scales}B). This stable average hides sensitive local comparisons: 2,628 of 8,235 specialty--model-pair comparisons (31.9\%) trigger the article-selection screen. A stable mean therefore does not make every specialty comparison stable. Nor does the contrast between centre and within-group results isolate a causal effect of scale.''',r'''Dentro de los grupos, la CKA media sigue rondando 0,63 para las áreas y 0,64 para las mismas 183 especialidades al pasar de 128 a 512 artículos (Figura~\ref{fig:scales}B). Esta media estable oculta comparaciones locales sensibles: 2.628 de las 8.235 comparaciones de especialidad y pareja de modelos (31,9\%) activan la alerta de selección de artículos. Una media estable no hace estable cada comparación de especialidades. Tampoco la diferencia entre centros y artículos individuales aísla un efecto causal de la escala.''','Hacer visible el 31,9 % de alertas locales en el cuerpo.','structure_subfield_stability_summary.csv')
setp(37,en[37]+r'''

Filtering source flags and duplicate components changes this picture little. Among the same retained starting papers, agreement rises from 30.58\% to 31.43\%, a gain of 0.85 percentage points. With candidate counts held fixed, the gains are 0.28 points at 1,024 and 0.19 at 2,048 candidates. The tested source issues do not account for most neighbour disagreement, although some areas change more than others (Table S19).''',es[37]+r'''

Filtrar las marcas de origen y los grupos de duplicados cambia poco este panorama. Entre los mismos artículos de partida conservados, el acuerdo sube del 30,58\% al 31,43\%: 0,85 puntos porcentuales. Al fijar la cantidad de candidatos, la subida es de 0,28 puntos con 1.024 y 0,19 con 2.048. Los problemas de origen cubiertos por este filtro no explican la mayor parte del desacuerdo entre vecinos, aunque algunas áreas cambian más que otras (Tabla S19).''','Cuantificar el efecto de calidad con las mismas consultas y tamaños.','quality_summary.csv')
en[37]=en[37].replace(r'\n\n','\n\n');es[37]=es[37].replace(r'\n\n','\n\n');changes[-1]['new_en']=en[37];changes[-1]['new_es']=es[37]
# Keep the original full-panel figure, but make the scope of its headline explicit.
setp(41,en[41].replace('Leaving out the abstract can matter as much as changing the model','Similar average changes hide different model behaviour').replace('These similar averages do not establish equivalence, but show that leaving out the abstract can matter about as much as the choice of model.','These averages describe this model panel; they do not establish equivalence or apply equally to each model.'),es[41].replace('Quitar el resumen puede importar tanto como cambiar el modelo','Medias parecidas ocultan comportamientos distintos entre modelos').replace('Estas medias parecidas no demuestran equivalencia, pero indican que quitar el resumen puede importar casi tanto como elegir otro modelo.','Estas medias describen este conjunto de modelos; no demuestran equivalencia ni se aplican por igual a cada modelo.'),'Limitar la comparación llamativa al promedio observado.','headline_summary.csv; headline_models.csv')
setp(42,en[42]+r'''

A direct neighbour check repeats fifty balanced selections of 1,000 candidates per area, half the full panel. At 25 neighbours, model change replaces 64.93\% and removing the abstract 66.49\%. The difference is 1.56 percentage points, with a central 95\% selection range of 1.44--1.69; its sign never reverses. The mean differences are 1.97 points at 10 neighbours and 1.04 at 50. Yet model-specific differences range from $-14.04$ points for MPNet to $+16.59$ for SciBERT. The stable grand mean conceals opposing model-specific results (Supplement S9).''',es[42]+r'''

Una comprobación directa de vecinos repite cincuenta selecciones equilibradas de 1.000 candidatos por área, la mitad de la muestra completa. Con 25 vecinos, cambiar de modelo sustituye el 64,93\% y quitar el resumen el 66,49\%. La diferencia es de 1,56 puntos porcentuales, con un rango central del 95\% entre selecciones de 1,44--1,69; el signo nunca se invierte. Las diferencias medias son de 1,97 puntos con 10 vecinos y 1,04 con 50. Sin embargo, la diferencia por modelo va de $-14,04$ puntos para MPNet a $+16,59$ para SciBERT. La media general estable oculta resultados opuestos entre modelos (Suplemento S9).''','Añadir una comprobación directa de vecinos y mostrar la heterogeneidad.','headline_summary.csv; headline_models.csv')
en[42]=en[42].replace(r'\n\n','\n\n');es[42]=es[42].replace(r'\n\n','\n\n');changes[-1]['new_en']=en[42];changes[-1]['new_es']=es[42]
setp(43,r'''Changing the rule that combines token outputs also reverses the average ordering. With CLS or SEP for the four word-level BERT models, removing the abstract changes fewer neighbours than changing models in every repetition: differences of $-3.13$ and $-2.00$ percentage points at 25 neighbours. Both the text comparison and its model-change reference change under these rules. The result concerns practical uses of the models, not an isolated causal effect of one processing step.''',r'''Cambiar la regla que combina las salidas de los tokens también invierte el orden medio. Con CLS o SEP en los cuatro BERT de palabras, quitar el resumen cambia menos vecinos que cambiar de modelo en todas las repeticiones: diferencias de $-3,13$ y $-2,00$ puntos porcentuales con 25 vecinos. Con estas reglas cambian tanto la comparación de texto como su referencia de cambio de modelo. El resultado se refiere a usos prácticos de los modelos, no al efecto causal aislado de un paso de procesamiento.''','Confirmar inversión por receta en las cincuenta repeticiones.','headline_summary.csv')
setp(47,en[47].split('\n\\PanelFigure')[0]+r'''
\PanelFigure{figure_04}{The answer depends on the representation as well as the model. Each bar covers all 325 area pairs. Blue means all ten models consistently identify the same area as larger; orange means at least two fixed models consistently give opposite answers; grey means unresolved. Each classification uses the main selection, twenty half samples and five further equal-size selections. The original and globally centred representations use identical articles. Centring subtracts the mean unit vector and then restores unit length. The 0 and 5\% cutoffs require relative differences above those values in every selection; they are not significance thresholds. All four cutoffs and the survival of the same opposing models are in Table S20.}{pairs}{1}''',es[47].split('\n\\PanelFigure')[0]+r'''
\PanelFigure{figure_04}{La respuesta depende de la representación además del modelo. Cada barra abarca las 325 parejas de áreas. Azul: los diez modelos señalan de forma consistente la misma área como mayor. Naranja: al menos dos modelos concretos dan respuestas opuestas de forma consistente. Gris: comparación sin resolver. Cada clasificación utiliza la selección principal, veinte mitades y cinco selecciones adicionales del mismo tamaño. Las representaciones original y centrada usan los mismos artículos. El centrado resta el vector unitario medio y después devuelve cada vector a longitud uno. Los cortes de 0 y 5\% exigen diferencias relativas superiores a esos valores en todas las selecciones; no son umbrales de significación. La Tabla S20 incluye los cuatro cortes y la conservación de los mismos modelos opuestos.}{pairs}{1}''','Mostrar el efecto adverso del centrado en una figura principal.','morphology_classification.csv; morphology_centering_summary.csv')
setp(48,r'''Alternative measures retain the same opposing models and directions in 225 of the 262 angular comparisons. With all 26 selections now available for dimension too, the entropy measure retains 209 of the 221 PR oppositions and D80 retains 190; 190 survive both alternatives. D80 counts directions as whole numbers, so ties remain unresolved. These related measures support many oppositions, not every area comparison or its thematic interpretation. Restricting the model panel to the six similarity-trained models still leaves 231 angular and 160 PR oppositions (Tables S14--S15).''',r'''Las medidas alternativas conservan los mismos modelos opuestos y sus direcciones en 225 de las 262 comparaciones angulares. Al disponer ahora de las 26 selecciones también para dimensión, la medida de entropía conserva 209 de las 221 oposiciones de PR y D80 conserva 190; 190 se mantienen con ambas alternativas. D80 cuenta direcciones con números enteros, por lo que los empates quedan sin resolver. Estas medidas relacionadas respaldan muchas oposiciones, no cada comparación entre áreas ni su interpretación temática. Restringir los modelos a los seis entrenados para similitud sigue dejando 231 oposiciones angulares y 160 de PR (Tablas S14--S15).''','Reemplazar la cobertura parcial por las 26 condiciones completas.','dimension_alternative_retention.csv; model_panel_summary_full_alternatives.csv')
setp(49,r'''Changing the vectors' reference point has a much larger effect on angular spread (Figure~\ref{fig:pairs}). After global centring and unit rescaling, persistent angular oppositions fall from 262 to 151. Of the original 262, 142 still have opposing models, but only 128 retain at least one of the same model pairs with the same directions; nine oppositions are new. Requiring differences above 5\% reduces angular opposition from 96 to 11. PR is less sensitive: its count changes from 221 to 211, with 204 original oppositions retaining the same models and directions. Angular spread is therefore strongly tied to this processing choice, rather than a property whose area ordering can be assumed to survive it.''',r'''Cambiar el punto de referencia de los vectores afecta mucho más a la apertura angular (Figura~\ref{fig:pairs}). Tras centrar globalmente y reajustar a longitud uno, las oposiciones angulares persistentes bajan de 262 a 151. De las 262 originales, 142 siguen teniendo modelos opuestos, pero solo 128 conservan al menos una de las mismas parejas de modelos con las mismas direcciones; nueve oposiciones son nuevas. Exigir diferencias superiores al 5\% reduce la oposición angular de 96 a 11. PR es menos sensible: pasa de 221 a 211, y 204 oposiciones originales conservan los mismos modelos y direcciones. La apertura angular está, por tanto, muy ligada a esta decisión de procesamiento; no podemos suponer que el orden entre áreas se mantendrá al cambiarla.''','Matiz material: apertura muy dependiente del procesamiento.','morphology_centering_summary.csv')
setp(54,r'''\subsection{What the additional checks change}
The controls sharpen the distinction between an average and a particular claim. Broad centre agreement survives article reselection, changes in size and omission of each area. The source-quality filter leaves most neighbour disagreement in place. The input comparison also repeats at the level of the grand mean, but its direction differs between models and changes with pooling. Saying that text and model matter equally would go beyond those results.

Angular spread needs an additional boundary: changing the common reference point changes many area comparisons, even when article-selection stability is required throughout. This does not make either representation the correct one. It means that the question being answered includes the processing choice. PR is less affected by that transformation, while alternative dimension measures still leave some comparisons unresolved.''',r'''\subsection{Qué cambian las comprobaciones adicionales}
Los controles precisan la diferencia entre una media y una afirmación concreta. El acuerdo entre centros resiste la elección de otros artículos, los cambios de tamaño y la omisión de cada área. El filtro de calidad deja intacta la mayor parte del desacuerdo entre vecinos. La comparación de entrada también se repite en la media general, pero su dirección difiere entre modelos y cambia con el pooling. Decir que texto y modelo importan por igual iría más allá de estos resultados.

La apertura angular necesita otro límite: cambiar el punto de referencia común cambia muchas comparaciones entre áreas, incluso exigiendo estabilidad ante la selección de artículos en todo el análisis. Esto no convierte una de las representaciones en la correcta. Significa que la pregunta que respondemos incluye la decisión de procesamiento. PR cambia menos con esa transformación, aunque las medidas alternativas de dimensión siguen dejando algunas comparaciones sin resolver.''','Integrar el resultado favorable y el adverso en la interpretación.','summary.json')
setp(60,r'''\section{Conclusion}
Changing the embedding model can preserve the broad arrangement of science while changing the papers found nearby and the direction of comparisons between areas. Removing an abstract can produce a similarly large average change, but that comparison depends on the model and pooling rule. Some results repeat with other articles yet change with the representation's processing, especially angular spread. For a claim drawn from a science map, the relevant check is whether that particular claim survives the choices that could affect it, with the size of the difference made clear. Agreement identifies what the tested representations share; establishing what is correct about the research requires evidence beyond them.''',r'''\section{Conclusión}
Cambiar el modelo de embeddings puede conservar la organización general de la ciencia y cambiar los artículos que encontramos cerca y el sentido de las comparaciones entre áreas. Quitar el resumen puede producir un cambio medio parecido, pero esa comparación depende del modelo y de la regla de pooling. Algunos resultados se repiten con otros artículos y, aun así, cambian con el procesamiento de la representación, especialmente la apertura angular. Para una afirmación extraída de un mapa, la comprobación pertinente es si esa afirmación concreta resiste las decisiones que pueden afectarla, dejando claro el tamaño de la diferencia. El acuerdo identifica qué comparten las representaciones probadas; establecer qué es correcto sobre la investigación exige evidencia externa a ellas.''','Alinear conclusión con las limitaciones comprobadas.','summary.json')
for folder,parts in [('manuscript',en),('manuscript_es',es)]:
 text='\n\n'.join(parts)
 text=text.replace(r'\section{Results}',r'\Needspace{14\baselineskip}'+ '\n' + r'\section{Results}').replace(r'\section{Resultados}',r'\Needspace{14\baselineskip}'+'\n'+r'\section{Resultados}')
 text=text.replace(r'\n\PanelFigure','\n'+r'\PanelFigure');(R/folder/'main.tex').write_text(text)
(HERE/'main_changes.json').write_text(json.dumps(changes,ensure_ascii=False,indent=2)+'\n')
print('Main text updated in both languages; title, citations and declarations retained.')
